/**
 * Fix Option - Represents a single fix strategy option for an issue.
 *
 * Each issue can have multiple FixOptions generated by the FixStrategyService.
 * The recommender selects the best option based on analysis context.
 */

import type { FixStrategy, Reversibility, EffortLevel, RiskLevel } from './issue-taxonomy';

export interface FixOption {
  /** Strategy identifier */
  strategy: FixStrategy;

  /** Human-readable label (e.g., "NULL로 변환") */
  label: string;

  /** Detailed description of what this fix does */
  description: string;

  /**
   * SQL template with placeholders.
   * null for strategies that don't produce SQL (manual, skip).
   */
  sqlTemplate: string | null;

  /** Whether this option is the recommended choice for the given context */
  isRecommended: boolean;

  /** Estimated effort level */
  effort: EffortLevel;

  /** Risk level of applying this fix */
  risk: RiskLevel;

  /** Human-readable impact description */
  impact: string;

  /** How reversible this fix is */
  reversibility: Reversibility;

  /**
   * SQL template for rolling back this fix.
   * null if reversibility is 'manual_only' or not applicable.
   */
  rollbackTemplate?: string | null;
}
